services:
  - type: web
    name: film-explorer-backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    autoDeploy: true