services:
  - type: web
    name: film-explorer-backend
    env: java
    plan: free
    region: frankfurt
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Xmx512m -Xms256m -jar target/film-explorer-0.0.1-SNAPSHOT.jar
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 21

databases:
  - name: film-explorer-db
    databaseName: filmexplorer
    user: filmuser
    region: frankfurt
    plan: free